spring.application.name=smartfarm-mng-app
server.port= 8001
spring.datasource.url=jdbc:mysql://localhost:3306/smartfarm_db
spring.datasource.username=root
spring.datasource.password=tenacioust!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql= true 
logging.level.org.hibernate.SQL = debug