spring.application.name=smartfarm-mng-app
server.port= 8001
spring.datasource.url=jdbc:mysql://localhost:3306/smartfarm_db
spring.datasource.username=root
spring.datasource.password=tenacioust!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql= true 
logging.level.org.hibernate.SQL = debug

# Mail Configuration (Environment Variables for Production)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:smartfarm.alerts@gmail.com}
spring.mail.password=${MAIL_PASSWORD:dummy_password_for_now}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true